openapi: 3.0.2
info:
  title: Games API
  version: 1.0.0
  description: |-
    ### This is a Swagger UI for our Games API  
    
    ### Error handling
    Errors are presented using the HTTP status codes 400-599. The response include a more detailed explanation about the error in the body.
    
    ```
    {
      "error": "Cleartext explanation of the error that occurred"
    }
    ```
    
    ### Generic API errors
    These error responses can be returned by any of the described endpoints.
    
    | HTTP status  |  Description |
    |---|---|
    | 400| Bad input parameters or invalid request. More information can be found in the response body.
    | 401| The consumer does not have access to the requested resource or the provided token is not valid.
    | 404| The requested resource can not be found or the user does not have access to the resource.
    | 5XX| A server error has occurred while processing the request.
paths:
  /games:
    description: ''
    get:
      tags:
      - games
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'
          description: Returns a list of all games
      summary: Get a list of all games
      description: Returns a list of all games in API
    post:
      tags:
      - new-game
      summary: Creates a game
      description: Creates a new game
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new-game'
            example:
              name: Tetris
              price: 0.99
      responses:
        '201':
          description: Game created successfully
          headers:
            Location:
              description: URL of the newly created game
              schema:
                type: string
                format: uri
              example: http://localhost:3000/games/9
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
              example:
                id: 9
                name: Tetris
                price: 0.99
        '400':
          description: One or all params are missing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                error: One or all params are missing
  /games/{id}:
    get:
      tags:
      - details
      summary: Get full details of a game
      description: Returns full details of a given id game
      operationId: id
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the game
        schema:
          type: integer
          minimum: 1
      responses:
        '200':
          description: Returns full details of a given id game
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Game'
              examples:
                Full details of a given game:
                  value:
                    id: 1
                    name: Witcher 3
                    price: 29.99
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              examples:
                Game was not found:
                  value:
                    error: Game not found
    delete:
      tags:
      - delete-game
      summary: Deletes a game
      description: Deletes a game by its ID
      parameters:
      - name: id
        in: path
        required: true
        description: ID of the game to delete
        schema:
          type: integer
          minimum: 1
      requestBody:
        description: Game to be deleted
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/delete-game'
            example:
              id: 2
      responses:
        '204':
          description: Game deleted successfully. No content.
        '404':
          description: Game was not found in games array
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
              example:
                error: Game not found
components:
  schemas:
    Game:
      type: object
      required:
      - id
      - name
      - price
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Witcher 3
        price:
          type: number
          format: float
          example: 29.99
    error:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          example: Game not found
    new-game:
      type: object
      required:
      - name
      - price
      properties:
        name:
          type: string
          example: Tetris
        price:
          type: number
          format: float
          example: 0.99
    delete-game:
      type: object
      required:
      - id
      properties:
        id:
          type: integer
          example: 2
